--- 
config_files: 
- from: nginx/brettnak.com.conf
  to: /etc/nginx/sites-availabl/brettnak.com.conf
  sudo: true

- from: nginx/thecarelesslovers.com.conf
  to: /etc/nginx/sites-availabl/thecarelesslovers.com.conf
  sudo: true

- from: nginx/nginx.conf
  to: /etc/nginx/nginx.conf
  sudo: true

working_server_directory: /home/brettnak/configuration
repository_url: https://brettnak@github.com/brettnak/BrettnakServer.git
host: thecarelesslovers.com
user: brettnak
